
baseURL = "https://harlogs.github.io/gridmov/"
languageCode = "en-us"
title = "Movies Manias"
theme = "custom"
[pagination]
  pagerSize = 10
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
